package handlers

import (
	"bufio"
	"bytes"
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/google/uuid"
	"gorm.io/gorm"

	"loomdeploy/internal/database"
	"loomdeploy/internal/docker"
	"loomdeploy/internal/logbroker"
	"loomdeploy/internal/models"
)

var nonAlphanumRE = regexp.MustCompile(`[^a-z0-9]+`)

func autoGenerateDomain(name string) string {
	baseDomain := os.Getenv("BASE_DOMAIN")
	if baseDomain == "" {
		baseDomain = "localhost"
	}
	slug := nonAlphanumRE.ReplaceAllString(strings.ToLower(name), "-")
	slug = strings.Trim(slug, "-")
	if len(slug) > 20 {
		slug = slug[:20]
	}
	shortID := uuid.NewString()[:6]
	return slug + "-" + shortID + "." + baseDomain
}

type createProjectRequest struct {
	Name           string            `json:"name" binding:"required"`
	Domain         string            `json:"domain"`
	SourceType     models.SourceType `json:"source_type"`
	RepositoryURL  string            `json:"repository_url"`
	Branch         string            `json:"branch"`
	ContainerPort  int               `json:"container_port"`
	GitToken       string            `json:"git_token"`
	CPULimit            float64           `json:"cpu_limit"`
	MemoryLimitMB       int               `json:"memory_limit_mb"`
	HealthCheckURL      string            `json:"health_check_url"`
	DockerfileContent   string            `json:"dockerfile_content"`
}

type updateProjectRequest struct {
	Name                   *string  `json:"name"`
	Domain                 *string  `json:"domain"`
	RepositoryURL          *string  `json:"repository_url"`
	Branch                 *string  `json:"branch"`
	ContainerPort          *int     `json:"container_port"`
	GitToken               *string  `json:"git_token"`
	NotificationWebhookURL *string  `json:"notification_webhook_url"`
	CPULimit               *float64 `json:"cpu_limit"`
	MemoryLimitMB          *int     `json:"memory_limit_mb"`
	HealthCheckURL         *string  `json:"health_check_url"`
	DockerfileContent      *string  `json:"dockerfile_content"`
}

func populateHasGitToken(projects []models.Project) {
	for i := range projects {
		projects[i].HasGitToken = projects[i].GitToken != ""
	}
}

func generateWebhookSecret() string {
	b := make([]byte, 20)
	_, _ = rand.Read(b)
	return hex.EncodeToString(b)
}

func setProjectFlags(p *models.Project) {
	p.HasGitToken = p.GitToken != ""
	p.HasWebhook = p.WebhookSecret != ""
}

func ListProjects(c *gin.Context) {
	userID := c.GetString("user_id")
	var projects []models.Project
	database.DB.Where("user_id = ?", userID).Find(&projects)

	for i := range projects {
		setProjectFlags(&projects[i])
		projects[i].WebhookSecret = ""
		var dep models.Deployment
		if err := database.DB.Where("project_id = ?", projects[i].ID).Order("started_at desc").First(&dep).Error; err == nil {
			projects[i].LatestDeployment = &dep
		}
	}
	c.JSON(http.StatusOK, projects)
}

func GetProject(c *gin.Context) {
	userID := c.GetString("user_id")
	var project models.Project
	if err := database.DB.Where("id = ? AND user_id = ?", c.Param("id"), userID).First(&project).Error; err != nil {
		c.JSON(http.StatusNotFound, gin.H{"message": "project not found"})
		return
	}
	setProjectFlags(&project)
	var dep models.Deployment
	if err := database.DB.Where("project_id = ?", project.ID).Order("started_at desc").First(&dep).Error; err == nil {
		project.LatestDeployment = &dep
	}
	c.JSON(http.StatusOK, project)
}

func CreateProject(c *gin.Context) {
	userID := c.GetString("user_id")
	var req createProjectRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"message": err.Error()})
		return
	}
	if req.Branch == "" {
		req.Branch = "main"
	}
	if req.ContainerPort == 0 {
		req.ContainerPort = 3000
	}
	if req.SourceType == "" {
		req.SourceType = models.SourceGit
	}

	domain := autoGenerateDomain(req.Name)
	isGenerated := true

	project := models.Project{
		ID:                uuid.NewString(),
		UserID:            userID,
		Name:              req.Name,
		Domain:            domain,
		IsGeneratedDomain: isGenerated,
		SourceType:        req.SourceType,
		RepositoryURL:  req.RepositoryURL,
		Branch:         req.Branch,
		ContainerPort:  req.ContainerPort,
		GitToken:       req.GitToken,
		WebhookSecret:  generateWebhookSecret(),
		CPULimit:            req.CPULimit,
		MemoryLimitMB:       req.MemoryLimitMB,
		HealthCheckURL:      req.HealthCheckURL,
		DockerfileContent:   req.DockerfileContent,
		CreatedAt:           time.Now(),
	}
	if err := database.DB.Create(&project).Error; err != nil {
		c.JSON(http.StatusConflict, gin.H{"message": "project with that domain already exists"})
		return
	}
	setProjectFlags(&project)
	c.JSON(http.StatusCreated, project)
}

func UpdateProject(c *gin.Context) {
	userID := c.GetString("user_id")
	var project models.Project
	if err := database.DB.Where("id = ? AND user_id = ?", c.Param("id"), userID).First(&project).Error; err != nil {
		c.JSON(http.StatusNotFound, gin.H{"message": "project not found"})
		return
	}

	var req updateProjectRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"message": err.Error()})
		return
	}

	updates := map[string]interface{}{}
	if req.Name != nil && *req.Name != "" {
		updates["name"] = *req.Name
	}
	if req.Domain != nil && *req.Domain != "" {
		updates["domain"] = *req.Domain
	}
	if req.RepositoryURL != nil {
		updates["repository_url"] = *req.RepositoryURL
	}
	if req.Branch != nil {
		updates["branch"] = *req.Branch
	}
	if req.ContainerPort != nil && *req.ContainerPort > 0 {
		updates["container_port"] = *req.ContainerPort
	}
	if req.GitToken != nil {
		updates["git_token"] = *req.GitToken
	}
	if req.NotificationWebhookURL != nil {
		updates["notification_webhook_url"] = *req.NotificationWebhookURL
	}
	if req.CPULimit != nil {
		updates["cpu_limit"] = *req.CPULimit
	}
	if req.MemoryLimitMB != nil {
		updates["memory_limit_mb"] = *req.MemoryLimitMB
	}
	if req.HealthCheckURL != nil {
		updates["health_check_url"] = *req.HealthCheckURL
	}
	if req.DockerfileContent != nil {
		updates["dockerfile_content"] = *req.DockerfileContent
	}

	if len(updates) == 0 {
		c.JSON(http.StatusBadRequest, gin.H{"message": "no fields to update"})
		return
	}

	if err := database.DB.Model(&project).Updates(updates).Error; err != nil {
		c.JSON(http.StatusConflict, gin.H{"message": "update failed: domain may already be taken"})
		return
	}

	database.DB.Where("id = ?", project.ID).First(&project)
	setProjectFlags(&project)
	c.JSON(http.StatusOK, project)
}

func RegenerateWebhook(c *gin.Context) {
	userID := c.GetString("user_id")
	var project models.Project
	if err := database.DB.Where("id = ? AND user_id = ?", c.Param("id"), userID).First(&project).Error; err != nil {
		c.JSON(http.StatusNotFound, gin.H{"message": "project not found"})
		return
	}
	newSecret := generateWebhookSecret()
	if err := database.DB.Model(&project).Update("webhook_secret", newSecret).Error; err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"message": "failed to regenerate"})
		return
	}
	c.JSON(http.StatusOK, gin.H{"webhook_secret": newSecret})
}

func DeleteProject(c *gin.Context) {
	userID := c.GetString("user_id")
	var project models.Project
	if err := database.DB.Where("id = ? AND user_id = ?", c.Param("id"), userID).First(&project).Error; err != nil {
		c.JSON(http.StatusNotFound, gin.H{"message": "project not found"})
		return
	}

	containerName := fmt.Sprintf("ld_%s", project.ID)
	docker.StopAndRemoveContainer(context.Background(), containerName)
	docker.RemoveImage(context.Background(), docker.TagForProject(project.ID))
	database.DB.Delete(&project)
	c.JSON(http.StatusOK, gin.H{"message": "project deleted"})
}

func DeployProject(c *gin.Context) {
	userID := c.GetString("user_id")
	var project models.Project
	if err := database.DB.Where("id = ? AND user_id = ?", c.Param("id"), userID).First(&project).Error; err != nil {
		c.JSON(http.StatusNotFound, gin.H{"message": "project not found"})
		return
	}

	var activeCount int64
	database.DB.Model(&models.Deployment{}).
		Where("project_id = ? AND status IN ?", project.ID, []string{string(models.StatusPending), string(models.StatusBuilding)}).
		Count(&activeCount)
	if activeCount > 0 {
		c.JSON(http.StatusConflict, gin.H{"message": "a deployment is already in progress"})
		return
	}

	var envVars []models.EnvVar
	database.DB.Where("project_id = ?", project.ID).Find(&envVars)

	dep := models.Deployment{
		ID:        uuid.NewString(),
		ProjectID: project.ID,
		Status:    models.StatusPending,
		StartedAt: time.Now(),
	}
	database.DB.Create(&dep)
	startDeployGoroutine(dep, project, envVars, "")
	c.JSON(http.StatusAccepted, dep)
}

func RedeployDeployment(c *gin.Context) {
	userID := c.GetString("user_id")
	var project models.Project
	if err := database.DB.Where("id = ? AND user_id = ?", c.Param("id"), userID).First(&project).Error; err != nil {
		c.JSON(http.StatusNotFound, gin.H{"message": "project not found"})
		return
	}

	var activeCount int64
	database.DB.Model(&models.Deployment{}).
		Where("project_id = ? AND status IN ?", project.ID, []string{string(models.StatusPending), string(models.StatusBuilding)}).
		Count(&activeCount)
	if activeCount > 0 {
		c.JSON(http.StatusConflict, gin.H{"message": "a deployment is already in progress"})
		return
	}

	var oldDep models.Deployment
	if err := database.DB.Where("id = ? AND project_id = ?", c.Param("depId"), project.ID).First(&oldDep).Error; err != nil {
		c.JSON(http.StatusNotFound, gin.H{"message": "deployment not found"})
		return
	}

	var envVars []models.EnvVar
	database.DB.Where("project_id = ?", project.ID).Find(&envVars)

	dep := models.Deployment{
		ID:        uuid.NewString(),
		ProjectID: project.ID,
		Status:    models.StatusPending,
		StartedAt: time.Now(),
	}
	database.DB.Create(&dep)
	startDeployGoroutine(dep, project, envVars, oldDep.CommitSHA)
	c.JSON(http.StatusAccepted, dep)
}

func DeleteDeployment(c *gin.Context) {
	userID := c.GetString("user_id")
	var project models.Project
	if err := database.DB.Where("id = ? AND user_id = ?", c.Param("id"), userID).First(&project).Error; err != nil {
		c.JSON(http.StatusNotFound, gin.H{"message": "project not found"})
		return
	}
	var dep models.Deployment
	if err := database.DB.Where("id = ? AND project_id = ?", c.Param("depId"), project.ID).First(&dep).Error; err != nil {
		c.JSON(http.StatusNotFound, gin.H{"message": "deployment not found"})
		return
	}
	active := dep.Status == models.StatusRunning || dep.Status == models.StatusBuilding || dep.Status == models.StatusPending
	if active {
		c.JSON(http.StatusConflict, gin.H{"message": "cannot delete an active deployment"})
		return
	}
	database.DB.Delete(&dep)
	c.JSON(http.StatusOK, gin.H{"message": "deployment deleted"})
}

func ListRecentDeployments(c *gin.Context) {
	userID := c.GetString("user_id")
	type Row struct {
		ID          string                  `json:"id"`
		ProjectID   string                  `json:"project_id"`
		ProjectName string                  `json:"project_name"`
		Status      models.DeploymentStatus `json:"status"`
		CommitSHA   string                  `json:"commit_sha,omitempty"`
		StartedAt   time.Time               `json:"started_at"`
		FinishedAt  *time.Time              `json:"finished_at,omitempty"`
	}
	var rows []Row
	database.DB.Table("deployments").
		Select("deployments.id, deployments.project_id, deployments.status, deployments.commit_sha, deployments.started_at, deployments.finished_at, projects.name as project_name").
		Joins("JOIN projects ON projects.id = deployments.project_id").
		Where("projects.user_id = ?", userID).
		Order("deployments.started_at DESC").
		Limit(15).
		Scan(&rows)
	c.JSON(http.StatusOK, rows)
}

func sendWebhookNotification(webhookURL, projectName string, status models.DeploymentStatus, sha string, dur time.Duration) {
	if webhookURL == "" {
		return
	}
	icon := "✅"
	if status != models.StatusRunning {
		icon = "❌"
	}
	msg := fmt.Sprintf("%s **%s** — deployment `%s`", icon, projectName, status)
	if len(sha) >= 7 {
		msg += fmt.Sprintf(" · commit `%s`", sha[:7])
	}
	dur = dur.Round(time.Second)
	m := int(dur.Minutes())
	s := int(dur.Seconds()) % 60
	if m > 0 {
		msg += fmt.Sprintf(" · took %dm %ds", m, s)
	} else {
		msg += fmt.Sprintf(" · took %ds", s)
	}
	payload, _ := json.Marshal(map[string]string{
		"text":    msg,
		"content": msg,
	})
	req, err := http.NewRequest(http.MethodPost, webhookURL, bytes.NewReader(payload))
	if err != nil {
		log.Printf("notification: bad webhook URL: %v", err)
		return
	}
	req.Header.Set("Content-Type", "application/json")
	client := &http.Client{Timeout: 5 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		log.Printf("notification webhook failed: %v", err)
		return
	}
	resp.Body.Close()
}

func ProjectContainerStats(c *gin.Context) {
	userID := c.GetString("user_id")
	var project models.Project
	if err := database.DB.Where("id = ? AND user_id = ?", c.Param("id"), userID).First(&project).Error; err != nil {
		c.JSON(http.StatusNotFound, gin.H{"message": "project not found"})
		return
	}

	var dep models.Deployment
	if err := database.DB.Where("project_id = ? AND status = ?", project.ID, models.StatusRunning).
		Order("started_at desc").First(&dep).Error; err != nil || dep.ContainerID == "" {
		c.JSON(http.StatusOK, gin.H{"message": "no running container"})
		return
	}

	stats, err := docker.GetContainerStats(context.Background(), dep.ContainerID)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"message": err.Error()})
		return
	}
	c.JSON(http.StatusOK, stats)
}

func startDeployGoroutine(dep models.Deployment, project models.Project, envVars []models.EnvVar, overrideSHA string) {
	go func() {
		var logs strings.Builder
		success := false
		containerID := ""
		resolvedSHA := ""

		publish := func(line string) {
			logs.WriteString(line)
			logbroker.Global.Publish(dep.ID, line)
		}

		defer func() {
			if r := recover(); r != nil {
				msg := fmt.Sprintf("\nFATAL: unexpected panic during deployment: %v\n", r)
				logs.WriteString(msg)
				logbroker.Global.Publish(dep.ID, msg)
			}
			logbroker.Global.Close(dep.ID)
			now := time.Now()
			status := models.StatusFailed
			if success {
				status = models.StatusRunning
			}
			database.DB.Model(&dep).Updates(models.Deployment{
				Status:      status,
				ContainerID: containerID,
				BuildLogs:   logs.String(),
				FinishedAt:  &now,
			})
			go sendWebhookNotification(project.NotificationWebhookURL, project.Name, status, resolvedSHA, now.Sub(dep.StartedAt))
		}()

		buildDir := filepath.Join(os.TempDir(), "builds", project.ID)
		_ = os.RemoveAll(buildDir)
		defer os.RemoveAll(buildDir)

		database.DB.Model(&dep).Update("status", models.StatusBuilding)

		if project.SourceType == models.SourceGit {
			token := project.GitToken
			if token == "" {
				if parsed, err := url.Parse(project.RepositoryURL); err == nil && parsed.Host != "" {
					host := strings.ToLower(parsed.Host)
					if idx := strings.LastIndex(host, ":"); idx != -1 {
						host = host[:idx]
					}
					var st models.SourceToken
					if database.DB.Where("provider = ?", host).First(&st).Error == nil {
						token = st.Token
					}
					// Fall back to GitHub App installation token
					if token == "" && strings.Contains(host, "github.com") {
						if ghTok, err := GetGitHubCloneToken(); err == nil && ghTok != "" {
							token = ghTok
						}
					}
				}
			}

			cloneURL := project.RepositoryURL
			if token != "" {
				if parsed, err := url.Parse(cloneURL); err == nil {
					parsed.User = url.UserPassword("x-access-token", token)
					cloneURL = parsed.String()
				}
			}

			cloneArgs := []string{"clone", "--branch", project.Branch}
			if overrideSHA == "" {
				cloneArgs = append(cloneArgs, "--depth=1")
			}
			cloneArgs = append(cloneArgs, cloneURL, buildDir)

			publish(fmt.Sprintf("Cloning %s (%s)...\n", project.RepositoryURL, project.Branch))
			out, err := exec.Command("git", cloneArgs...).CombinedOutput()
			publish(string(out))
			if err != nil {
				outStr := strings.ToLower(string(out))
				isAuthErr := strings.Contains(outStr, "authentication failed") ||
					strings.Contains(outStr, "could not read username") ||
					strings.Contains(outStr, "permission denied") ||
					strings.Contains(outStr, "repository not found") ||
					strings.Contains(outStr, "invalid username or password") ||
					strings.Contains(outStr, "remote: not found")
				if isAuthErr {
					publish("ERROR: This repository may be private. Add a token for this provider in Settings → Source Control.\n")
				} else {
					publish(fmt.Sprintf("git clone failed: %v\n", err))
				}
				return
			}

			if overrideSHA != "" {
				publish(fmt.Sprintf("Rolling back to commit %s...\n", overrideSHA[:7]))
				checkOut, checkErr := exec.Command("git", "-C", buildDir, "checkout", overrideSHA).CombinedOutput()
				publish(string(checkOut))
				if checkErr != nil {
					publish(fmt.Sprintf("ERROR: could not checkout %s: %v\n", overrideSHA, checkErr))
					return
				}
			}

			shaBytes, _ := exec.Command("git", "-C", buildDir, "rev-parse", "HEAD").Output()
			resolvedSHA = strings.TrimSpace(string(shaBytes))
			if resolvedSHA != "" {
				database.DB.Model(&dep).Update("commit_sha", resolvedSHA)
				publish(fmt.Sprintf("Commit: %s\n", resolvedSHA[:7]))
			}

			if _, statErr := os.Stat(filepath.Join(buildDir, "Dockerfile")); os.IsNotExist(statErr) {
				if project.DockerfileContent != "" {
					publish("No Dockerfile in repo — using project's custom Dockerfile override...\n")
					if werr := os.WriteFile(filepath.Join(buildDir, "Dockerfile"), []byte(project.DockerfileContent), 0644); werr != nil {
						publish(fmt.Sprintf("ERROR: could not write Dockerfile: %v\n", werr))
						return
					}
				} else {
					framework := docker.DetectFramework(buildDir)
					if framework == "" {
						publish("ERROR: No Dockerfile found and framework could not be auto-detected.\n")
						publish("Add a Dockerfile to your repo root, or set a custom Dockerfile in project Settings → Dockerfile Override.\n")
						publish("Supported auto-detect: Node.js (package.json), Python (requirements.txt/pyproject.toml), Go (go.mod), Ruby (Gemfile), PHP (composer.json), Java Maven (pom.xml), Java Gradle (build.gradle), Static HTML (index.html — served via nginx on port 80).\n")
						return
					}
					publish(fmt.Sprintf("No Dockerfile found — auto-detected framework: %s. Injecting template...\n", framework))
					tmpl := docker.DockerfileTemplate(framework, buildDir, project.ContainerPort)
					if werr := os.WriteFile(filepath.Join(buildDir, "Dockerfile"), []byte(tmpl), 0644); werr != nil {
						publish(fmt.Sprintf("ERROR: could not write Dockerfile: %v\n", werr))
						return
					}
				}
			}
		} else {
			publish("Upload-based deployment: no source directory found\n")
			return
		}

		imageTag := docker.TagForProject(project.ID)
		publish(fmt.Sprintf("Building image %s...\n", imageTag))

		archive, err := docker.CreateBuildArchive(buildDir)
		if err != nil {
			publish(fmt.Sprintf("Archive error: %v\n", err))
			return
		}
		defer archive.Close()

		ctx := context.Background()
		buildOut, err := docker.BuildImage(ctx, archive, imageTag)
		if err != nil {
			publish(fmt.Sprintf("Build error: %v\n", err))
			return
		}
		defer buildOut.Close()

		scanner := bufio.NewScanner(buildOut)
		for scanner.Scan() {
			line := scanner.Text()
			var msg map[string]json.RawMessage
			if json.Unmarshal([]byte(line), &msg) == nil {
				if errRaw, ok := msg["error"]; ok {
					var errStr string
					_ = json.Unmarshal(errRaw, &errStr)
					publish("ERROR: " + errStr + "\n")
					return
				}
				if streamRaw, ok := msg["stream"]; ok {
					var s string
					_ = json.Unmarshal(streamRaw, &s)
					if s != "" {
						publish(s)
					}
				} else if statusRaw, ok := msg["status"]; ok {
					var s string
					_ = json.Unmarshal(statusRaw, &s)
					if idRaw, ok2 := msg["id"]; ok2 {
						var id string
						_ = json.Unmarshal(idRaw, &id)
						publish(s + " " + id + "\n")
					} else {
						publish(s + "\n")
					}
				}
			} else {
				publish(line + "\n")
			}
		}

		publish("Starting container...\n")

		envSlice := make([]string, 0, len(envVars))
		for _, e := range envVars {
			envSlice = append(envSlice, fmt.Sprintf("%s=%s", e.Key, e.Value))
		}

		var extraDomains []models.ProjectDomain
		database.DB.Where("project_id = ?", project.ID).Find(&extraDomains)
		extraSlice := make([]string, 0, len(extraDomains))
		for _, d := range extraDomains {
			extraSlice = append(extraSlice, d.Domain)
		}

		cid, err := docker.RunContainer(ctx, docker.RunConfig{
			ProjectID:     project.ID,
			ImageTag:      imageTag,
			Domain:        project.Domain,
			ExtraDomains:  extraSlice,
			ContainerPort: project.ContainerPort,
			EnvVars:       envSlice,
			CPULimit:      project.CPULimit,
			MemoryLimitMB: int64(project.MemoryLimitMB),
		})
		if err != nil {
			publish(fmt.Sprintf("Container run error: %v\n", err))
			return
		}

		retiredAt := time.Now()
		database.DB.Model(&models.Deployment{}).
			Where("project_id = ? AND id != ? AND status = ?", project.ID, dep.ID, models.StatusRunning).
			Updates(map[string]interface{}{"status": models.StatusStopped, "finished_at": &retiredAt})

		containerID = cid
		success = true
		publish(fmt.Sprintf("Deployment complete. Container: %s\n", cid[:12]))
	}()
}

func ContainerAction(c *gin.Context) {
	userID := c.GetString("user_id")
	action := c.Param("action")

	var project models.Project
	if err := database.DB.Where("id = ? AND user_id = ?", c.Param("id"), userID).First(&project).Error; err != nil {
		c.JSON(http.StatusNotFound, gin.H{"message": "project not found"})
		return
	}

	var dep models.Deployment
	if err := database.DB.Where("project_id = ?", project.ID).Order("started_at desc").First(&dep).Error; err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"message": "no deployment found"})
		return
	}

	if err := docker.ContainerAction(context.Background(), dep.ContainerID, action); err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"message": err.Error()})
		return
	}

	targetStatus := models.StatusRunning
	if action == "stop" {
		targetStatus = models.StatusStopped
	}
	database.DB.Model(&dep).Update("status", targetStatus)
	c.JSON(http.StatusOK, gin.H{"message": fmt.Sprintf("container %sed", action)})
}

func ListDeployments(c *gin.Context) {
	userID := c.GetString("user_id")
	var project models.Project
	if err := database.DB.Where("id = ? AND user_id = ?", c.Param("id"), userID).First(&project).Error; err != nil {
		c.JSON(http.StatusNotFound, gin.H{"message": "project not found"})
		return
	}
	var deps []models.Deployment
	database.DB.Where("project_id = ?", project.ID).Order("started_at desc").Find(&deps)
	c.JSON(http.StatusOK, deps)
}

func ListEnvVars(c *gin.Context) {
	userID := c.GetString("user_id")
	var project models.Project
	if err := database.DB.Where("id = ? AND user_id = ?", c.Param("id"), userID).First(&project).Error; err != nil {
		c.JSON(http.StatusNotFound, gin.H{"message": "project not found"})
		return
	}
	var vars []models.EnvVar
	database.DB.Where("project_id = ?", project.ID).Find(&vars)
	c.JSON(http.StatusOK, vars)
}

type envVarInput struct {
	Key   string `json:"key" binding:"required"`
	Value string `json:"value"`
}

func SetEnvVars(c *gin.Context) {
	userID := c.GetString("user_id")
	var project models.Project
	if err := database.DB.Where("id = ? AND user_id = ?", c.Param("id"), userID).First(&project).Error; err != nil {
		c.JSON(http.StatusNotFound, gin.H{"message": "project not found"})
		return
	}

	var inputs []envVarInput
	if err := c.ShouldBindJSON(&inputs); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"message": err.Error()})
		return
	}

	database.DB.Transaction(func(tx *gorm.DB) error {
		tx.Where("project_id = ?", project.ID).Delete(&models.EnvVar{})
		for _, v := range inputs {
			tx.Create(&models.EnvVar{
				ID:        uuid.NewString(),
				ProjectID: project.ID,
				Key:       v.Key,
				Value:     v.Value,
			})
		}
		return nil
	})

	var vars []models.EnvVar
	database.DB.Where("project_id = ?", project.ID).Find(&vars)
	c.JSON(http.StatusOK, vars)
}

func StreamBuildLogs(c *gin.Context) {
	userID := c.GetString("user_id")
	var project models.Project
	if err := database.DB.Where("id = ? AND user_id = ?", c.Param("id"), userID).First(&project).Error; err != nil {
		c.JSON(http.StatusNotFound, gin.H{"message": "project not found"})
		return
	}

	var dep models.Deployment
	if err := database.DB.Where("project_id = ? AND status IN ?", project.ID, []string{string(models.StatusPending), string(models.StatusBuilding)}).Order("started_at desc").First(&dep).Error; err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"message": "no active build"})
		return
	}

	c.Header("Content-Type", "text/event-stream")
	c.Header("Cache-Control", "no-cache")
	c.Header("Connection", "keep-alive")
	c.Header("X-Accel-Buffering", "no")

	ch := logbroker.Global.Subscribe(dep.ID)
	defer logbroker.Global.Unsubscribe(dep.ID, ch)

	ctx := c.Request.Context()
	for {
		select {
		case line, ok := <-ch:
			if !ok {
				fmt.Fprintf(c.Writer, "event: done\ndata: \n\n")
				c.Writer.(http.Flusher).Flush()
				return
			}
			fmt.Fprintf(c.Writer, "data: %s\n\n", strings.ReplaceAll(line, "\n", "\ndata: "))
			c.Writer.(http.Flusher).Flush()
		case <-ctx.Done():
			return
		}
	}
}

func StreamContainerLogs(c *gin.Context) {
	userID := c.GetString("user_id")
	var project models.Project
	if err := database.DB.Where("id = ? AND user_id = ?", c.Param("id"), userID).First(&project).Error; err != nil {
		c.JSON(http.StatusNotFound, gin.H{"message": "project not found"})
		return
	}

	var dep models.Deployment
	if err := database.DB.Where("project_id = ?", project.ID).Order("started_at desc").First(&dep).Error; err != nil || dep.ContainerID == "" {
		c.JSON(http.StatusBadRequest, gin.H{"message": "no running container"})
		return
	}

	c.Header("Content-Type", "text/event-stream")
	c.Header("Cache-Control", "no-cache")
	c.Header("Connection", "keep-alive")

	ctx, cancel := context.WithCancel(c.Request.Context())
	defer cancel()

	reader, err := docker.StreamLogs(ctx, dep.ContainerID)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"message": err.Error()})
		return
	}
	defer reader.Close()

	scanner := bufio.NewScanner(reader)
	for scanner.Scan() {
		line := scanner.Text()
		if len(line) > 8 {
			line = line[8:]
		}
		fmt.Fprintf(c.Writer, "data: %s\n\n", line)
		c.Writer.(http.Flusher).Flush()
	}
}
